label stm32mp257f-dk-buildroot
  kernel /boot/Image.gz
  devicetree /boot/stm32mp257f-dk.dtb
  append root=PARTUUID=b26967be-18fb-40fe-9d9b-ae035fc4a1c5 rootwait rw quiet clk_ignore_unused console=ttySTM0,115200n8
